# Generated by Django 6.0.1 on 2026-02-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_department',
            new_name='add_dept',
        ),
    ]
