# Generated by Django 6.0.1 on 2026-02-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_querys'),
    ]

    operations = [
        migrations.AddField(
            model_name='querys',
            name='admin_reply',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='querys',
            name='query',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
