# Generated by Django 6.0.1 on 2026-02-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_querys_admin_reply_alter_querys_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='querys',
            name='status',
            field=models.CharField(default='pending', max_length=90),
        ),
        migrations.AlterField(
            model_name='querys',
            name='query',
            field=models.CharField(max_length=50),
        ),
    ]
